### ISSUE TITLE
Optinally Suppress the number of items in a group 

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#1]
ag-grid automatically adds the number of records in a group 

+ Sweden (5)
+ Germany (17)

HTML is as follows:

```
<span class="ag-group-value" ref="eValue">English</span>
<span class="ag-group-child-count" ref="eChildCount">(26)</span>
```

We'd like to add an option to the BBj Plug-In

```
setShowGroupChildCount( 1/0 )
```

that toggles the display of the group count.

**Comment by hyyan** [comment]
@StephanWald I have added a simple bbj implementation for `setShowGroupChildCount` , you can review it and when it is OK we can close the issue

**Comment by StephanWald** [comment]
fixed
