### ISSUE TITLE
add row filtered row count and row count to the grid 

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#100]
Can we add the row count (and if filtered the visible row count) to the grid control itself. Maybe to the low-right corner, and when you hover with the mouse make it disappear (in case it hides actual data) ?
Something like "17 rows" or "2 of 17 rows" if filtered down to only two rows ?

**Comment by hyyan** [comment]
@StephanWald  Are we talking about the [Status Bar Component](https://www.ag-grid.com/javascript-grid-status-bar/)

**Comment by StephanWald** [comment]
That would be a great addition! add a setShowStatusBar(1/0) to the grid plugin itself.

We may later even add an additional string parameter that the programer can use to display custom status messages...

**Comment by StephanWald** [comment]
@hyyan some customers would appreciate if you could make this one your next focus after fixing the thing you're working on.
