### ISSUE TITLE
apply "numericColumn" to numeric columns 

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#117]
ag grid has a flag "numericColumn" in the column definition API, that right-aligns the column header and the column contents. Apply this one to numeric columns.

**Comment by hyyan** [comment]
The current column definition implementation in BBj does not support types, the numeric column is type which just adds CSS class for cells and the header to align the content to the right, we can implement a method for this in BBj without introducing types

This is what the grid does under the hood:

**Comment by hyyan** [comment]
Closing in favor of `setColumnHeaderAlignment()` & `setColumnAlignment`
