### ISSUE TITLE
allow controlling colours etc for entire row, entire column

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#132]
Currently this is only possible per cell. Need the same per column, per row for performance reasons

**Comment by StephanWald** [comment]
How should we output them? Simply inside the meta element, or in a sub-element inside meta?

```
   "NUMBEROFTRACKS":12,
      "ONHAND":55,
      "COST":5.99,
      "RETAIL":12.99,
      "meta":{
         **"BGCOLOR":"#00FFEE",**
         "CDNUMBER":{
            "ColumnType":"12",
            "EDITABLE":"1"
         },
         "TITLE":{
            "ColumnType":"12",
            "EDITABLE":"1"
         },
```

**Comment by hyyan** [comment]
@StephanWald There are no real performance issues with cells solution.
I opened an issue on [BasisHub/components](https://github.com/BasisHub/components/issues/144 ) for propsed structure
