### ISSUE TITLE
Add new `addColumn` method signature 

### ISSUE THREAD

**Issue by hyyan** [BBj-Plugins/BBjGridExWidget#133]
```java
method public void addColumn(DataRow row!)
```

**Comment by hyyan** [comment]
@StephanWald  do you think it is a good idea?

**Comment by StephanWald** [comment]
What's the use case, and how would you use it in the context of a real life program?

**Comment by hyyan** [comment]
Allow developers to compose the whole data row then adding it directly to the grid as the grid starts with an empty Resultset by default.
Ag grid is changing a lot of options from being global options to being column specific options. an example would `sortable , resizable , ...` .  Keep adding new method signatures for all these options does not seems to be the right path.

Take a look at how complex this can get 

```java
method public void addColumn(
BBjString Field$, 
BBjString Label$, 
BBjNumber Type!, 
BBjNumber Editable!,
BBjNumber Sortable!,
BBjNumber Resizable!,
....
)

**Comment by StephanWald** [comment]
The existing nethod setAttributesRecord is intended to do this. It can be improved insofar that it already prepares the grid layout before the setData is happening. In the current implementation it's only presenting the auto-setter and it's only honored when setData is called. We ought to implement "setAttributesRecord" explicitly and do the prep-work as you suggest at that time already.

**Comment by hyyan** [comment]
The idea is the DataRow
