### ISSUE TITLE
parser null object error

### ISSUE THREAD

**Issue by RVDHOFAUDEV** [BBj-Plugins/BBjGridExWidget#141]
![image](https://user-images.githubusercontent.com/5030352/57986771-7095ae80-7a79-11e9-9ae2-56772af20035.png)

Hello, sudden internal error in BBjGridExWidgetRow...

BBj SysConsole
Server BBj Version: REV 18.21
Server Build: 03/26/2019 11:56
Client BBj Version: REV 18.21
Client Build: 03/26/2019 11:56
Serial Number: BBX624373
Copyright BASIS International Ltd.
!ERROR=252  (Attempt to invoke method 'parse' on null object)
[35]         ar! = parser!.parse(str(#asDataRow().toJson())).getAsJsonArray()
 
READY
[4]C:/bbj/plugins/BBjGridExWidget/BBjGridExWidgetRow.bbj>

**Comment by hyyan** [comment]
@RVDHOFAUDEV valid bug, [it is the code order](https://github.com/BBj-Plugins/BBjGridExWidget/blob/master/BBjGridExWidgetRow.bbj#L35-L37). the parser should be initialized before we start parsing the data row.

I will resolve later today or tomorrow but Pull Requests are more than welcome, I will approve

**Comment by RVDHOFAUDEV** [comment]
Sorry, also to busy to contribute such projects

 

 

 
Mit freundlichen Grüßen, vriendelijke groeten, best regards

Ralf van den Heuvel
Information analyst / Developer

r.vandenheuvel@audev.com / 0049 6051 836952 / 0031 8590 2370 5
 <http://twitter.com/caritdms> 


 <http://www.audev.com/> 

Von: Hyyan Abo Fakher <notifications@github.com> 
Gesendet: Montag, 20. Mai 2019 09:18
An: BBj-Plugins/BBjGridExWidget <BBjGridExWidget@noreply.github.com>
Cc: Ralf van den Heuvel <r.vandenheuvel@audev.com>; Mention <mention@noreply.github.com>
Betreff: Re: [BBj-Plugins/BBjGridExWidget] parser null object error (#141)

 

@RVDHOFAUDEV <https://github.com/RVDHOFAUDEV>  valid bug, it is the code order <https://github.com/BBj-Plugins/BBjGridExWidget/blob/master/BBjGridExWidgetRow.bbj#L35-L37> . the parser should be initialized before we start parsing the data row.

I will resolve later today or tomorrow but Pull Requests are more than welcome, I will approve

**Comment by RVDHOFAUDEV** [comment]
Danke

 

 
Mit freundlichen Grüßen, vriendelijke groeten, best regards

Ralf van den Heuvel
Information analyst / Developer

r.vandenheuvel@audev.com / 0049 6051 836952 / 0031 8590 2370 5
 <http://twitter.com/caritdms> 


 <http://www.audev.com/> 

Von: Hyyan Abo Fakher <notifications@github.com> 
Gesendet: Montag, 20. Mai 2019 20:50
An: BBj-Plugins/BBjGridExWidget <BBjGridExWidget@noreply.github.com>
Cc: Ralf van den Heuvel <r.vandenheuvel@audev.com>; Mention <mention@noreply.github.com>
Betreff: Re: [BBj-Plugins/BBjGridExWidget] parser null object error (#141)

 

Closed #141 <https://github.com/BBj-Plugins/BBjGridExWidget/issues/141>  via  <https://github.com/BBj-Plugins/BBjGridExWidget/commit/22c09668ae3e19cd9818c8d8ffd2ef9a5a8a89e3> 22c0966.
