### ISSUE TITLE
Refactoring -  Columns Management

### ISSUE THREAD

**Issue by hyyan** [BBj-Plugins/BBjGridExWidget#142]
@StephanWald 

**This plan is just a theoretical implementation for discussion. I might still be missing some details and the final implementation (if approved) might differ a bit.**

We need to refactor the code which handles columns creation and parsing. such a change(big one) will touch several methods which were there (most implemented by you)  from the early stage.
including the following methods 

* `setData( ResultSet rs!)`
* `setData( ResultSet rs! ,BBjString RowNodeId$)`
* `setRowsData(ResultSet rs!)`
* `performGridDataUpdate()`
* `getAgGridColumnDefinition`

**Motivation** 
* Get rid of the internal several DataRow(s) `#AttributesRecord!` , `#ColumnDefinition!` , `#AdditionalAttributes!`.  we should have only one ColumnDefinition(DataRow).
* `getAgGridColumnDefinition` cannot be extended without limitless if-else statements and cannot be documented for BBj developers. the method works as a black box. it is not really clear what field attribute to use in order to get the filtering, pivot, grouping,.. working correctly.
* If you use the method `setColumn`, you cannot retrieve the column again to alter its information to enable/disable sorting or filtering...  
I know this can be done from the resultset but it is not ideal.
* BBj developers cannot control or alter the grid settings we build for the client, we should allow this for edge cases.
* The grid depends on the  `Resultset` as a model for the data management but this should be wrapped completely by the Grid so bbj developers will not need to manipulate the resultset directly, they should be able to feed the grid a resultset then manipulate/extend it directly from the Grid.
* #133 I opened then closed it really fast as I was missing some information.
* Several issues mentioned here and there like column alignment not working, column filters can not disabled ... 

**The Plan**
* Introduce `Column` class.
In theory, this one should work as the [DataField](https://basishub.github.io/components/javadoc/) class (Probably extension) but in a less confusing way in the grid context. the  `Column` class should be serializable and can be converted to JSON like ag-grid column definition. plus the class will implement several methods to help setting field attributes like `filter`, `sort`, `aggFunc`,...
We can document the class so developers can know what is supported and what is not.
* Introduce Columns Manager (Probably dataRow extension)
  The class can add remove,.. columns and build a final like columns definition. then we merge this one with the first row of the fed resultset. 
* The `BBjGridExWidget.bbj` will implement several helper methods for columns manipulation

**Comment by StephanWald** [comment]
AdditionalAttributes! had been introduced to keep the AttributesRecord free from internal additions. It can be refactored by making the AttributesRecord immutable and then directly manipulating it when needed in similar convenience methods like the image list.
