### ISSUE TITLE
trying to destroy an already destroyed BBjExGridWidget it throws an err=252

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#170]
From the bbj developer list - please review in dev and see if the problem still exists 

when trying to destroy an already destroyed BBjExGridWidget it throws an err=252, throw I set an Error handler:

[1]WEG2/WEG21195>grid!.destroy(err=*Proceed)
!ERROR=252  (java.lang.RuntimeException: com.basis.bbj.client.util.BBjException: Attempting to call a method on a destroyed object)  
[257]         #Canvas!.destroy()         

To test, add a button to a grid demo "Destroy" that calls destroy() twice. The second call shall not throw an error but be a NO OP.

**Comment by hyyan** [comment]
@StephanWald This is the default behavior for all BBj Controls, you cannot destroy what is already destroyed.  the method [BBjControl::isDestroyed](https://documentation.basis.com/BASISHelp/WebHelp/winmethods/bbjcontrol/bbjcontrol_isdestroyed.htm) should be used , the grid inherit these methods from [BBjWidget](https://github.com/BBj-Plugins/BBjWidget)

**Comment by StephanWald** [comment]
evidence that this is standard BBj behavior:

```
wnd! = BBjAPI().openSysGui("X0").addWindow(10,10,800,600,"TEST")
btn! = wnd!.addButton(100,10,10,250,250,"TEST")
btn!.destroy()
btn!.destroy()
```

However, we might immediately want to throw the error in the widget instead of in the internal code. Re-opening. We need to check for "isDestroyed()" and if so actively throw 252 "already destroyed" to the outside world
