### ISSUE TITLE
What is the replacment of the GRID.setAttributesRecord(DataRow) method - concept?

### ISSUE THREAD

**Issue by RVDHOFAUDEV** [BBj-Plugins/BBjGridExWidget#171]
Best NEW practice to inject the column attributes to the grid?
What is the replacement of the  GRID.setAttributesRecord(DataRow) method?????

**Comment by hyyan** [comment]
@RVDHOFAUDEV Use the columns API. The `setAttributesRecord` was used to configure the grid columns. in the latest version, this is can be done by using the columns API directly.
ex :

**Setting Column Mask:**
```java 
double! = grid!.getColumn("DOUBLE")
double!.getValueFormatterExpression().setMask("##,##0.00")
```

**Setting Image Renderer**
```java
 use ::BBjGridExWidget/BBjGridExWidgetRenderers.bbj::BBjGridExWidgetRendererImageRenderer

 jsonIcons!    = new JsonObject()
 jsonIcons!       .addProperty("ID_1","/path/img_1.png")
 jsonIcons!       .addProperty("ID_1","/path/img_2.png")

 icon!      = grid!.getColumn("ICON")
 icon!.setCellRenderer(new BBjGridExWidgetRendererImageRenderer(jsonIcons!))
```

If you have common settings you want to share between all columns, then use the `DefaultColumnDefinition`
```java
grid!.getDefaultColumnDefinition().setWidth(500)
```
