### ISSUE TITLE
use ::BBjGridExWidget/BBjGridWidgetCellEditingEvent.bbj::BBjGridWidgetCellEditingEvent MISSING

### ISSUE THREAD

**Issue by RVDHOFAUDEV** [BBj-Plugins/BBjGridExWidget#172]
The file BBjGridWidgetCellEditingEvent.bbj is currently not part of the package - That is why our program crashs! Please add it again!

In practice is the current code crashing:

> 	method public void cellEditingStarted(BBjCustomEvent xx!)
> 		#info(#signature$+" - cellEditingStarted")
> 		declare BBjGridWidgetCellEditingEvent ev!
> 		**ev! = cast(BBjGridWidgetCellEditingEvent,xx!.getObject())**
> 		#editStateValue! = new Boolean(ev!.getValue())
> 	methodend

**Comment by hyyan** [comment]
@RVDHOFAUDEV The latest version of the plugin is a major update, classes and APIs are changed.
This class was replaced with `::BBjGridExWidget/BBjGridExWidgetClientEvents.bbj::BBjGridExWidgetClientEventsCell`
