### ISSUE TITLE
various questions around the column attributes, types etc. - concept?

### ISSUE THREAD

**Issue by RVDHOFAUDEV** [BBj-Plugins/BBjGridExWidget#173]
Hi, thanks for the information so far - also about grid!.getColumn("FOO") which accepts to set a ResultSet first into the grid to got some column for getting...

Would like to addColumns... in the initialization proper to the attributes delivered by a business component according to the ResultSet which will be served by the BC a bbit later.

Now (since setAttributes(..) is no longer supported), I have to add the columns.
Here a various question about this topic:

a) 

> public BBjGridExWidgetColumn(BBjString field!,
> BBjString label!,
> BBjNumber type!)
> Create a new column defintion
> Parameters:
> BBjString - field! The field of the row to get the cells data from
> BBjString - label! The name to render in the column header
> BBjNumber - type! The field's type
What is type! Can you provide a link to the details about type! Thought in the beginning this means to apply java.sql.types.VARCHAR etc, but it isn't.

b)
before putting the ResultSet to the grid, I tried to modify the first DataRow object only and add some attributes like LABEL to see the translated text. 
But I can't see any change - the label of 
dr!.setFieldAttribute("EMPLOYEE_ID","LABEL","Employee")
is not visible. The Grid shows EMPLOYEE_ID instead of Employee.

c) 
I can apply something like this...
> c!=new BBjGridExWidgetColumn("IS_ACTIVE","activated"); REM ,java.sql.types.BOOLEAN
> #grid!.addColumn(c!)
 I would like to add the  render attributes like once applied of 
RENDERER_TRUE = switch
RENDERER_FALSE = switch
How to add Attributes to the  BBjGridExWidgetColumn ?
Okay, now I see a 'BBjGridExWidgetRendererInterface' but I can't recognize to use it in the 'BBjGridExWidgetColumnDefinition' .
Can you provide a short example?

Hope, you will get time to write down some short examples beside the given demos in the java doc. And the demos got space of improvement (like mine created stuff as well :-)). It would be welcome to provide object orientated version of the demo include DECLARE statements for each object in order to keep it transparent and understandable for a newbie using the GRID.

Thank you

**Comment by RVDHOFAUDEV** [comment]
Ah, okay the attribute name is case sensitive.
hence b) is solved - using attribute 'Label' instead of 'LABEL' works

**Comment by hyyan** [comment]
@RVDHOFAUDEV 

**a )** `type!` is a java SQL type. the default column type if none was provided or detected from the ResultSet is `java.sql.Types.VARCHAR` (12).
The following are the supported SQL types (anything else will be ignored):
1. java.sql.Types.BIGINT
2. java.sql.Types.BIT
3. java.sql.Types.DECIMAL
4. java.sql.Types.DOUBLE
5. java.sql.Types.FLOAT
6. java.sql.Types.INTEGER
7. java.sql.Types.NUMERIC
8. java.sql.Types.NUMERIC
9. java.sql.Types.TINYINT
10. java.sql.Types.DATE
11. java.sql.Types.TIMESTAMP
12. java.sql.Types.TIMESTAMP_WITH_TIMEZONE
13. java.sql.Types.BOOLEAN

**b )** You can aslo set the label from the API 
```java
rem // if column is already added from the resultset
grid!.getColumn("EMPLOYEE_ID").setLabel("Employee")

rem // if the column is set before we provide a resultset
grid!.addColumn("EMPLOYEE_ID","Employee")
grid!.setData(ResultSet!)
```

**c)** The `DataTypesDemo.bbj` shows how to use boolean renderers
by default, the grid will attach the correct renderer for each column based on its type.
You can get the instance of the attached cell renderer like 
```java
use ::BBjGridExWidget/BBjGridExWidgetRenderers.bbj::BBjGridExWidgetRendererBoolean

declare BBjGridExWidgetRendererBoolean renderer!
renderer! = grid!.getColumn("IS_ACTIVE").getCellRenderer()
```
in your case the column type is `java.sql.Types.BOOLEAN` then the grid will attache the boolean renderer automatically to the column. You can manipulate the renderer like : 
```java
 use ::BBjGridExWidget/BBjGridExWidgetRenderers.bbj::BBjGridExWidgetRendererBoolean

  boolean!  = grid!.getColumn("IS_ACTIVE")
  boolean!.getCellRenderer().setTrueValue(BBjGridExWidgetRendererBoolean.SWITCH_RENDERER())
  boolean!.getCellRenderer().setFalseValue(BBjGridExWidgetRendererBoolean.SWITCH_RENDERER())
```
Currenlty the grid comes with few predefined renderers , [defined in here](https://bbj-plugins.github.io/BBjGridExWidget/javadoc/BBjGridExWidget/Renderers/package-frame.html)

HTH
