### ISSUE TITLE
setData is overriding defined cell renderers for existing columns

### ISSUE THREAD

**Issue by RVDHOFAUDEV** [BBj-Plugins/BBjGridExWidget#174]
![image](https://user-images.githubusercontent.com/5030352/61976998-841b4380-afed-11e9-9c5f-17e9aac94f3e.png)

... would like to get that behavior again - the booleans should only being shown using such fancy slidering balls. I can't manage to get it back. Need your tips..

so far my new code looks like the following. But it does not the job so far:

> 		c!=new BBjGridExWidgetColumn("IS_INCOMING","incoming calls",java.sql.Types.BOOLEAN)
> 		r!=cast(BBjGridExWidgetRendererBoolean,c!.getCellRenderer()); REM inteface BBjGridExWidgetRendererInterface impl. class
> 		r!.setTrueValue(BBjGridExWidgetRendererBoolean.SWITCH_RENDERER())
> 		r!.setFalseValue(BBjGridExWidgetRendererBoolean.SWITCH_RENDERER())
> 		#grid!.addColumn(c!) 

What can I do? Thank you  (using actually the latest development MASTER)

**Comment by hyyan** [comment]
@RVDHOFAUDEV I think you are building the columns and then calling `setData(ResultSet!)` after that.
The `setData` will override your cell renderer in this case.
I see some space for improvements for such cases  I will improve this hopefully in the next version.

To solve your problem with the current version, you have two options :
1. Make sure to configure the cell renderer after calling `setData`
```java
  c!=new BBjGridExWidgetColumn("IS_INCOMING","incoming calls",java.sql.Types.BOOLEAN)
  #grid!.addColumn(c!) 
  #grid!.setData(ResultSet)

  r!=cast(BBjGridExWidgetRendererBoolean,c!.getCellRenderer()); REM inteface BBjGridExWidgetRendererInterface impl. class
  r!.setTrueValue(BBjGridExWidgetRendererBoolean.SWITCH_RENDERER())
  r!.setFalseValue(BBjGridExWidgetRendererBoolean.SWITCH_RENDERER())
```
2. If you are building the columns from scratch and you do not need the grid to auto configure the columns for you based on the ResultSet then use `setRS(ResultSet)` instead.

```java 
  c!= grid!.addColumn("IS_INCOMING","incoming calls",java.sql.Types.BOOLEAN)
  r!=cast(BBjGridExWidgetRendererBoolean,c!.getCellRenderer()); REM inteface BBjGridExWidgetRendererInterface impl. class
  r!.setTrueValue(BBjGridExWidgetRendererBoolean.SWITCH_RENDERER())
  r!.setFalseValue(BBjGridExWidgetRendererBoolean.SWITCH_RENDERER())
  grid!.addColumn(c!) 

  grid!.setRS(ResultSet)
```
