### ISSUE TITLE
setRS(..) will not refresh the content of the grid when applied the second time

### ISSUE THREAD

**Issue by RVDHOFAUDEV** [BBj-Plugins/BBjGridExWidget#175]
Hi, my last current problem is that setData(rs!) will refresh the content of the grid with the effect tha t my previous column definitions get lost, which were set up before.
Because I am going to setup the columns from scratch here before applying setRS(rs!) this needs to refresh the complete content of the grid when called the second time, too - without loosing the previous prepared column data.

Thought to solve the problem when doing a setRS(rs!) with a following updateColumn(..). But I am wrong. Could not find a method like simply refresh().

Thx

**Comment by hyyan** [comment]
@RVDHOFAUDEV the `setRS` method is just a setter method. it does not have any magic behind it. You can force rendering by calling the [render ](https://bbj-plugins.github.io/BBjGridExWidget/javadoc/BBjGridExWidget/BBjGridExWidget.html#render--) method

```java
grid!.addColumn(...)
grid!.setRS(rs!)
grid!.render()
```

**Note** on the first initialization, you do not need to call `render()`  . the grid will wait for `process_events` to start and then render itself automatically 

Here is a runnable demo you can try :

```java
use ::BBjGridExWidget/BBjGridExWidget.bbj::BBjGridExWidget
use com.basiscomponents.db.ResultSet
use com.basiscomponents.bc.SqlQueryBC

? 'HIDE'

declare auto BBjTopLevelWindow wnd!
declare BBjGridExWidget grid!

wnd! = BBjAPI().openSysGui("X0").addWindow(10,10,800,600,"Render Demo")
wnd!.setCallback(BBjAPI.ON_CLOSE,"byebye")

onRenderAgain! = wnd!.addButton(200,10,10,150,25,"Render Again")
onRenderAgain!.setCallback(BBjAPI.ON_BUTTON_PUSH,"onRenderAgain")

gosub main
process_events

main:
  declare SqlQueryBC sbc!
  declare ResultSet rs!
  
  sbc! = new SqlQueryBC(BBjAPI().getJDBCConnection("CDStore"))
  rs! = sbc!.retrieve("SELECT CDNUMBER , TITLE FROM CDINVENTORY")
  
  REM init the grid
  grid! = new BBjGridExWidget(wnd!,100,0,50,800,550)

  grid!.addColumn("CDNUMBER","ID")
  grid!.setRS(rs!)
  REM // No need for this on the first initialization 
  REM   grid!.render()
return

onRenderAgain:
    grid!.addColumn("TITLE" , "THE TITLE")
    grid!.render()
return

byebye:
bye
```
