### ISSUE TITLE
add masking/ cell renderer for Timestamp

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#18]
see https://raw.githubusercontent.com/BBj-Plugins/BBjGridExWidget/master/Demo/DatatypesDemo.bbj

DATE type works, TIMESTAMP needs attention

**Comment by StephanWald** [comment]
http://documentation.basis.com/BASISHelp/WebHelp/commands/date_function_bbj.htm

**Comment by hyyan** [comment]
Fixed via dc3bdcb5b49c9b5acd59cb4f5d16e512f9d0b6f4
