### ISSUE TITLE
Status of the plugin - refactoring completed?

### ISSUE THREAD

**Issue by RVDHOFAUDEV** [BBj-Plugins/BBjGridExWidget#180]
Hi, 
is the refactoring completed now?
Can we trust, that you/Basis is no longer removing methods in the plugin which are already in the productive field outside at the customers?

As you know - we are still missing the old and very handy - from our perspective - method 'setAttributesRecord(..)'.  - we are forced to write something this for our own on top! That is annoying and the acceptance to use the grid rel. to the ResultSet Approach might suffer.

Thank you for your reply in advance - I have to modify some progs / to repair them. 

best regards
Ralf

**Comment by StephanWald** [comment]
We're sorry to hear that the refactor during the alpha version development did bite you quite a bit. As soon as we're publishing a stable first release we'll stay away from changing methods without a proper deprecation-time ahead.
In terms of the Attributes Record, this will have to go to your implementation of the grid. We recommend to implement a class that extends the grid widget for this use case, as we demonstrate in the CustomGridDemo 

We might in the future provide a grid implementation for the BusinessComponents architecture paradigm in that realm, but it does not belong into this core grid, which we do not want to pollute with specific implementations to suit a particilar framework concept.

We appreciate your contribution!
