### ISSUE TITLE
adjust masking / cell renderer to BBx type masks

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#19]
see https://raw.githubusercontent.com/BBj-Plugins/BBjGridExWidget/master/Demo/DatatypesDemo.bbj

The mask for numeric values does not work as expected.
Customers would want to use BBx specific masking.  See http://documentation.basis.com/BASISHelp/WebHelp/usr/numeric_output.htm

**Comment by hyyan** [comment]
Fixed via dc3bdcb5b49c9b5acd59cb4f5d16e512f9d0b6f4
