### ISSUE TITLE
removeRow(by numeric value) - but how to get the current line number?

### ISSUE THREAD

**Issue by RVDHofDAGOCAR** [BBj-Plugins/BBjGridExWidget#198]
#### What product versions and settings are you using when this issue occurs?
* BBj: 18.21
* BBjGridExWidget: 0.100.4
* Platform (GUI or BUI): GUI
* Browser:

#### Steps to Reproduce
1. callback when doublecliking a cell
1. can't get the numeric index of the double clicked row
1. therefore unable to delete the row by using 'removeRow(BBjNumber')'

#### What I Expected

chance to get the numeric line index 0,1,2,3,4,5, etc of the double clicked line
or overload of removeRow(row!.getIndex()) or removeRow(row!.getId())

#### What Happened Instead
how to perform?

	method public void onGridDoubleClick(BBjCustomEvent ev!)
        declare auto BBjGridExWidgetClientEventsCell e!
        declare auto BBjGridExWidgetClientRowModel row!
        declare auto BBjGridExWidgetClientColumnModel column!
        declare DataRow dr!
        **e!=ev!.getObject(); REM most wanted
        row! = e!.getRow(); REM most wanted**
        dr!=cast(DataRow,row!.asDataRow()); REM most wanted
        REM column! = e!.getColumn()
        REM value$ = e!.getValue().toString()
        REM isSelected = row!.getIsSelected()
        REM parentKey$ = row!.getParentKey()
        index$ = row!.getIndex()
        id$ = row!.getId()
        REM childIndex = row!.getChildIndex()
        PRIM_KEY$=dr!.getFieldAsString("PRIM_KEY")
        DESCR$=dr!.getFieldAsString("DESCR")
            **rowIndex = ?????????
            #grid!.removeRow(rowIndex)**
        fi
    methodend

**Comment by hyyan** [comment]
@RVDHofDAGOCAR **removeRow** method currently requires the index of the row inside the grid, so something like this should work for you:

```java
grid!.removeRow(row!.getChildIndex())  
```

One thing to mention is that the removeRow method will not work anymore once you start sorting the data in the grid which is a bug #186

**Comment by hyyan** [comment]
Duplicates of #186
