### ISSUE TITLE
allow theme selection and custom CSS for embedded ag-grid

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#2]

**Comment by StephanWald** [comment]
added getThemes and setTheme

**Comment by hyyan** [comment]
@StephanWald These methods change the grid class name and does not inject theme files.
To make this work we need like `injectScript` method to inject CSS files if this not possible then 
all theme files must be injected as a string in the `redraw` method even though this is ugly

**Comment by hyyan** [comment]
@StephanWald This issue is partially resolved, the grid supports two methods `addStyle` and `remove style`
to add and remove style, these two methods can be used to override specific parts of an existing theme
