### ISSUE TITLE
allow to change selection by simple cursor up-down

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#20]
when grid!.setMultipleSelection(0) is set, it would be nice if you could move the selection bar with a simple cursor arrow up/down keypress. Can we make that happen?

**Comment by hyyan** [comment]
@StephanWald  I think this is natively available in ag-grid and we do not need to do anything 

Using Arrow keys [up/down] navigates throw the rows, pressing [space] will select the row 
The behavior can be tested on `ColumnSetupDemo`
