### ISSUE TITLE
implement getAllVisibleRows after filtering using the quick search for instance

### ISSUE THREAD

**Issue by RVDHofDAGOCAR** [BBj-Plugins/BBjGridExWidget#200]
Hello Hyyan, 
is there a way to get the visible rows only after performing any filtering?
Would like to delete those rows finally which has been selected before.
Is something like this maybe already implement?
Would be perfect to got an option to iterate through such collection of 
filtered rows and visible rows.
Thank you
best regards
Ralf

**Comment by hyyan** [comment]
@RVDHofDAGOCAR You can select all filtered rows using [selecteAll(BBjNumber filtered!)](https://bbj-plugins.github.io/BBjGridExWidget/javadoc/BBjGridExWidget/BBjGridExWidget.html#selectAll-BBjNumber-) and then you can iterate over them by calling  [getSelectedRows()](https://bbj-plugins.github.io/BBjGridExWidget/javadoc/BBjGridExWidget/BBjGridExWidget.html#getSelectedRows--)
