### ISSUE TITLE
Restrict number of rows in demos to not run into OOM exceptions

### ISSUE THREAD

**Issue by RalphLance** [BBj-Plugins/BBjGridExWidget#217]
#### What product versions and settings are you using when this issue occurs?
* BBj: Latest internal trunk (Development) version (20.40BETA)
* BBjGridExWidget: Latest master
* Platform (GUI or BUI): Everything local GUI on Windows 10 with AdoptOpenJDK 11.0.9.101
* Browser: N/A

#### Steps to Reproduce
1. Run GridExWidget Demo.bbj via button in PluginManager.
2. Choose a database and table with many large records (in this case a test of Audev CarIT CUSTOMER table).

#### What I Expected
Presentation of the data in the grid.

#### What Happened Instead
BBj process suddenly just disappeared. Found mention of "client memory exceeded" in the BBj debug log. Have -Xmx8g -Xms1g JVM options for local BBjServices. Suggest limiting number of rows retreived to an arbitrary (500? 1000? 2500?), which may be acceptable for a demo, or offering a configurable limit. Then a status bar or popup message that this number has been reached, thus the resulting data is limited accordingly.

**Comment by hyyan** [comment]
@RalphLance  Shahidur fixed this
