### ISSUE TITLE
when a MASK with a leading minus sign (-) is passed, the SGN of the displayed number is wrong

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#22]
This is a BBJ specifix issue: Masks that start with "-" indicate that a minus sign should be displayed for negative numbers. The JS implementation of the bbj masks show the minus for positive numbers and suppress it for negative numbers.

**Comment by hyyan** [comment]
The issue is not specific to this project, so moved to [bbj-masks](https://git.storesandbox.de/hyyan/bbj-masks/issues/1)
