### ISSUE TITLE
Cell editor does not correctly set after calling .setData(data!)

### ISSUE THREAD

**Issue by mjuryeci** [BBj-Plugins/BBjGridExWidget#242]
#### What product versions and settings are you using when this issue occurs?
* BBj: 22.03
* BBjGridExWidget: 1.10.1
* Platform (GUI or BUI): GUI

#### Steps to Reproduce
1. set initial grid data
2. make columns editable and set column editors
3. set new grid data
4. (failed work-around) set column editors again

#### What I Expected
The correct column selector (GxCellEditorSelect) to be set

#### What Happened Instead
the standard text cell editor. I even printed out the value of column!.getCellEditor().getCellEditorName() and it read "agSelectCellEditor", even though it wasn't

**Comment by hyyan** [comment]
@mjuryeci 

[The BBjGridExWidget::setData method](https://bbj-plugins.github.io/BBjGridExWidget/docs/data/overview)

> Because BBjGridExWidget::setData builds the column definition from the ResultSet, it overrides all the column components (renderers, editors, and formatters) and their configuration unless they are part of the DataRow attributes. To get around this, configure the columns after calling this method.

To update the grid's data , use one of the methods described in the [Managing Data](https://bbj-plugins.github.io/BBjGridExWidget/docs/data/managing-data) section
