### ISSUE TITLE
[Bug]COLLISION IN GRID IDENTIFIERS (BUI/DWC)

### ISSUE THREAD

**Issue by B3sTP4gAn0** [BBj-Plugins/BBjGridExWidget#251]
**#RootId! NAME COLLIDES in BUI/DWC**

When loading two independent BBjGridExWidget simultaneously in the same browser tab (for example from an MDI menu) in BUI or DWC environment, collision is generated in the identifiers of each BBjGridExWidget and consequently the programs cannot make reference to their own grid.

The `BBjGridExWidget.getRootId()` method generates collisions on grid names, because the instance counter is reset with each new bbj session loaded. So the two sessions will create the identifier ***gx-grid-1*** for two different grids in the same browser tab.

**To Reproduce**

1. Go to 'menu' in the menubar
2. Click on 'grid1'
3. Click on 'grid2'

**Expected behavior**
Having the application ***grid1.bbj*** with BBjGridExWidget and loading the application ***grid2.bbj***, the information from ***grid2.bbj*** is loaded into ***grid1.bbj***.

Also, all programming regarding the BBjGridExWidget in ***grid2.bbj*** will manipulate the BBjGridEx in ***grid1.bbj***

**Screenshots**
![error_1](https://user-images.githubusercontent.com/49003254/212349824-6021eb2e-f518-45e8-b7ab-9fb124ad13e0.png)

![error_2](https://user-images.githubusercontent.com/49003254/212349482-4eb5fd00-bac8-4a0f-bee1-bc1293e8d2d4.png)

**Temporary fix in BBjGridExWidget.getRootId()**

To fix temporary then problem, i make sure that each generated grid  contains a unique name.
In the following way:

https://github.com/BBj-Plugins/BBjGridExWidget/blob/30a502cc14ac6cf3d7bdfbf27e68ca789bcad50f/BBjGridExWidget.bbj#L865

```#RootId! = "gx-grid-" + java.util.UUID.randomUUID().toString() + str(#InstanceCount!)```

**Desktop:**
 - OS: Window 11, Linux Mint (5.4.0-88-generic)
-  java: openjdk version "11.0.8" 2020-07-14
 - BBj: 21.12
 - BBjGridExWidget version: 1.11.0
 - Platform: BUI/DWC
 - Browser: chrome, firefox

**Sample Programs**
In this particular example, ***menu.bbj*** must be executed from a BUI environment.

***menu.bbj***
```java
REM /**
REM  * menu.bbj
REM  * @author bryan
REM  *
REM  */

?'hide'

declare auto BBjSysGui gui!
declare auto BBjTopLevelWindow win!
declare auto BBjGridExWidget grid!
declare auto BBjMenuBar mBar!
declare auto BBjMDI mdi!

gui! = BBjAPI().openSysGui("X0")
w = gui!.getSystemMetrics().getScreenBounds().getWidth()
h = gui!.getSystemMetrics().getScreenBounds().getHeight()

mdi! = BBjAPI().getMDI()
mdi!.createMDIWindow(0, 0, w, h, "Menu Principal",$00001083$)
mdi!.setBackColor(BBjAPI().makeColor(255,255,255))
mdi!.setTitleBarVisible(Boolean.FALSE)

menuBar! = mdi!.addMenuBar()
menu! = menuBar!.addMenu(1,"MENU")

item1! = menu!.addMenuItem(1, "grid1")
item1!.setCallback(BBjAPI().ON_MENU_ITEM_SELECT,"loadPGM1")

item2! = menu!.addMenuItem(2, "grid2")
item2!.setCallback(BBjAPI().ON_MENU_ITEM_SELECT,"loadPGM2")

PROCESS_EVENTS

loadPGM1:
    x = scall("bbj grid1.bbj &")
return

loadPGM2:
    x = scall("bbj grid2.bbj &")
return

byebye:
    bye
```

***grid1.bbj***
```java
REM /**
REM  * grid1.bbj
REM  * @author bryan
REM  *
REM  */

?'hide'

use ::BBjGridExWidget/BBjGridExWidget.bbj::BBjGridExWidget

use com.basiscomponents.db.ResultSet
use com.basiscomponents.bc.SqlQueryBC

declare BBjSysGui gui!
declare auto BBjTopLevelWindow win!
declare BBjGridExWidget grid!

gui! = BBjAPI().openSysGui("X0")

win! = gui!.addWindow(5, 5, 800, 600, pgm(-1), $40010003$)
win!.setAlwaysOnTop(Boolean.TRUE)

gosub createGrid
gosub setCallbacks

process_events  

createGrid:
    declare SqlQueryBC sbc!
    declare ResultSet rs!
    declare BBjGridExWidget grid!
    sbc! = new SqlQueryBC(BBjAPI().getJDBCConnection("CDStore"))
    rs! = sbc!.retrieve("SELECT * FROM CDINVENTORY")
    grid! = new BBjGridExWidget(win!, 100, 0, 0, 800, 600)
    grid!.setData(rs!)
return

setCallbacks:
    win!.setCallback(BBjAPI.ON_CLOSE,"byebye")
    grid!.setCallback(BBjGridExWidget.ON_GRID_DOUBLE_CLICK(),"onGridDoubleClick")
return

onGridDoubleClick:
    x = msgBox("grid!.getRootId(): " + grid!.getRootId(),0,pgm(-1))
return

byebye:
    bye
```

***grid2.bbj***
```java
REM /**
REM  * grid2.bbj
REM  * @author bryan
REM  *
REM  */

?'hide'

use ::BBjGridExWidget/BBjGridExWidget.bbj::BBjGridExWidget

use com.basiscomponents.db.ResultSet
use com.basiscomponents.bc.SqlQueryBC

declare BBjSysGui gui!
declare auto BBjTopLevelWindow win!
declare BBjGridExWidget grid!

gui! = BBjAPI().openSysGui("X0")

win! = gui!.addWindow(200, 200, 800, 600, pgm(-1), $40010003$)
win!.setAlwaysOnTop(Boolean.TRUE)

gosub createGrid
gosub setCallbacks

process_events  

createGrid:
    declare SqlQueryBC sbc!
    declare ResultSet rs!
    declare BBjGridExWidget grid!
    sbc! = new SqlQueryBC(BBjAPI().getJDBCConnection("ChileCompany"))
    rs! = sbc!.retrieve("SELECT * FROM CUSTOMER")
    grid! = new BBjGridExWidget(win!, 100, 0, 0, 800, 600)
    grid!.setData(rs!)
return

setCallbacks:
    win!.setCallback(BBjAPI.ON_CLOSE,"byebye")
    grid!.setCallback(BBjGridExWidget.ON_GRID_DOUBLE_CLICK(),"onGridDoubleClick")
return

onGridDoubleClick:
    x = msgBox("grid!.getRootId(): " + grid!.getRootId(),0,pgm(-1))
return

byebye:
    bye
```

**Comment by hyyan** [comment]
@B3sTP4gAn0 Thanks for reporting. A fix is available in version `v1.11.1`
