### ISSUE TITLE
Two cosmetic bugs in BBjGridExWidget plugin version 1.12.0

### ISSUE THREAD

**Issue by BhaveshatAudev** [BBj-Plugins/BBjGridExWidget#253]
**Describe the bug**
1. In GxOptions.bbj there are  2 methods having same name and same return type "method public static BBjNumber getInstanceCount()".
2. In BBjGridExWidget.getInstanceCount() method, there is a error in string concatenation.

**To Reproduce**
Compile both programs.

**Expected behavior**
No errors in compilation

**Screenshots**

![2_deprecated_methods_in_GxOptions](https://user-images.githubusercontent.com/128801346/227498082-f80ae5d7-b7bf-42ff-8d78-3804746b0d5a.png)
![String_concatenation_error_in_BBjGridExWidget](https://user-images.githubusercontent.com/128801346/227498129-00b8320c-58a9-4780-9748-d9a3a4d1bd49.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - BBj: 2214
 - BBjGridExWidget version: 1.12.0
 - Platform (GUI or BUI): GUI

**Comment by StephanWald** [comment]
That's a valid complaint, we may not have two methods in the same class with the same signature.  BBj does not compile this class without errors.
