### ISSUE TITLE
Missing Translation for "Blank" and "Not blank"

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#259]
![image003](https://github.com/BBj-Plugins/BBjGridExWidget/assets/4833070/325fdfb8-0533-49cd-9fd8-93f1cc38fbac)

**Comment by hyyan** [comment]
In which version is this ?  The newest version include the translation for these words.

https://github.com/BBj-Plugins/BBjGridExWidget/blob/dev/langs/de_DE.json#L9-L10
