### ISSUE TITLE
enhance datatypes demo to show different boolean representations

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#26]

**Comment by hyyan** [comment]
Resolved via 3b2317475c7bc4f7c09fb7e8cb72e1ccf6401e2e

**Comment by hyyan** [comment]
@StephanWald See https://github.com/BBj-Plugins/BBjGridExWidget/blob/master/Demo/DatatypesDemo.bbj#L52-L56
