### ISSUE TITLE
Request: Implement "Many Editors One Column"

### ISSUE THREAD

**Issue by mjuryeci** [BBj-Plugins/BBjGridExWidget#261]
**Is your feature request related to a problem? Please describe.**
As far as I can tell after combing through the docs, the ability to conditionally set the cell editor based on row data is not supported. Since editable grids with dropdowns are not supported in BUI standard grid, I started rewriting one of our grids to this new AG Grid, only to find out that we are unable to set up cell editors conditionally. [AG grid supports writing a callback to conditionally set the editor based on row data.](https://www.ag-grid.com/javascript-data-grid/cell-editors/#many-editors-one-column)

**Describe the solution you'd like**
Perhaps a function on GxColumn: 
```addConditionalEditor(GxColumn columnToChangeEditor, String fieldNameInRowToCheck, String matchValue, GxCellEditorInterface cellEditorToSetIfMatch)```
This can add an if statement to the cellEditorSelector callback on the AG Grid column as stated in their docs. There is probably a better solution than this but this one seems straight forward.

**Describe alternatives you've considered**
I have considered extending the existing classes like GxColumn to unlock this functionality, but there seems to be no happy path to get there without extending a large chunk of the entire plugin. I also tried my hand at changing the cell editor right as the user starts editing the cell, but this results in the different editors flashing on/off screen, and can lead to inconsistent data.

**Additional context**
https://www.ag-grid.com/javascript-data-grid/cell-editors/#many-editors-one-column

**Comment by hyyan** [comment]
@mjuryeci Currently, there are no plans to add this feature, and there is no straightforward method to incorporate it into the BBjGridExWidget.
