### ISSUE TITLE
need a demo that shows more fancy cell rendering

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#27]
...like setting an image / icon inside a cell

**Comment by hyyan** [comment]
The old [DatatypesDemo.bbj](https://github.com/BBj-Plugins/BBjGridExWidget/blob/refactor-2/Demo/DatatypesDemo.bbj) on `refactor-2` branch contained what you are asking for, but it seems those two branches are not synced anymore, I'm having a hard time fixing this.
I will add something  when everything is fixed

**Comment by hyyan** [comment]
@StephanWald `DatatypesDemo.bbj` contains this now
