### ISSUE TITLE
Timestamp data is skewed in GUI, okay in BUI

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#38]
In DatatypesDemo.bbj there is a TIMESTAMP column with value "2018-01-02 12:22:13"
The grid shows 02.01.2018 13:22:13 (as of today, sitting in CET time zone)

created Bug [31491](https://bugzilla.basis.com/show_bug.cgi?id=31491) - The BBjHTMLView (JavaFX WebView) is not initialized with the same time zone as the interpreter

**Comment by hyyan** [comment]
@StephanWald  can we consider this one resolved ?!
