### ISSUE TITLE
allow updating one single row

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#39]
Currently, the only way to update single values is a setData to the full grid. We want to offer a method that updates a single row:
- the developer updates the value(s) inside the existing ResultSet
- we add an updateRow(x) that sends the new row data to the grid and re-renders the row only
- consider to only redraw the cells that have really changed

**Comment by hyyan** [comment]
See `DataUpdateDemo.bbj`
