### ISSUE TITLE
setColumnWidth does not work correctly when left column is pinned or grid is treegrid

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#4]
setColumnWidth

![image](https://user-images.githubusercontent.com/4833070/32314045-2302f586-bfa6-11e7-87a9-e2bebbddc79b.png)

**Comment by hyyan** [comment]
@StephanWald 

After digging into this issue, I found that this is the case only for tree demo.
`setColumnWidth` will work with tree demo with the following code 

```java
dt! = new DataTree()
.....
grid!.setColumnWidth("__node__name",800)
grid!.setData(dt!)
```

I have also updated `setColumnWidth` to be able to update a column width after the grid is rendered, so a full grid re-render is not required to update only a column width
