### ISSUE TITLE
add more control over tree

### ISSUE THREAD

**Issue by atimmbeu** [BBj-Plugins/BBjGridExWidget#6]
Bonjour,

Je n'ai pas trouvé de paramètre qui me permettrait de déployer un nœud au départ de mon affichage comme la commande du BBjTree . Il me faudrait les méthodes "expandNode" et "expandTreeFromNode"

D'un point de vue général, toutes les méthodes du BBjTree sont intéressantes et si vous pouvez les intégrer au Widget alors ce serait super.

**Comment by hyyan** [comment]
@StephanWald  I think this should be closed as we are going to deprecate the Tree feature anyway

**Comment by StephanWald** [comment]
Issue closed. The current implementation will be deprecated/frozen, in favor of the more powerful Enterprise features.
