### ISSUE TITLE
setSelectedRow or setSelectedRows does not update the SelectedRowsMap

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#69]
Run the new, enhanced selection demo. The "SHOW SEL" button now lists the result of getSelectedRows. It is (now) correct for any selection that the user made with the mouse, but it shows nothing after a programmatic selection with setSelectedRow(s).

(prior to this fix it even showed the now wrong, old user selection. Added a call to "deleselectAll" to fix that aspect at least...)

**Comment by hyyan** [comment]
@StephanWald It seems you pushed none required code. 
when the bbj method `setSelectedRow` || `setSelectedRows` is called, a selection change event will be fired back to bbj after the call to update the selection map, so you do not need to call `deleselectAll`

After investigating the issues it seems that chromium is not sending the selection change event back to BBj. but BUI & JavaFX does.

I will try to isolate the issue, this is an ugly one and it will take time.

**Comment by StephanWald** [comment]
Looks like programatically selected rows never end up in the map:  https://www.screencast.com/t/fwVQB5vfX  Marking this as high priority...
