### ISSUE TITLE
Locale setting (SETOPTS?) broken for numeric masks  / values

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#71]
This seems to have been broken recently. When setting a !LOCALE in the program, like "nl_NL" the dates but esp the masks of the numbers seem unaffected. The sample also contains SETOPTS code that should flip the comma and the decimal, but doesn't.

**Comment by hyyan** [comment]
@StephanWald setting the `!LOCALE`  does not affect the numbers  comma/dot setting 
as the feature is language-independent .

To configure numbers separators you need to use  `SETOPTS` as in `DatatypesDemo.bbj`
To configure date formatting according the language you need to use  `!LOCALE` as in `EditingDemo.bbj`
