### ISSUE TITLE
Remove TreeDemo.bbj

### ISSUE THREAD

**Issue by hyyan** [BBj-Plugins/BBjGridExWidget#77]
We need to deprecate this demo , this demo is not working anymore

**Comment by hyyan** [comment]
@StephanWald  do you have any plans regarding this one, currently, there is no chance to make this work. the demo is broken since we implemented the row indexing in basiscomponents.

Maybe we should think about supporting the [Enterprise feature ](https://www.ag-grid.com/javascript-grid-tree-data/)

**Comment by hyyan** [comment]
@StephanWald  The demo is removed by ad9073324966e4c2b238e306a0bd80db1136eab1 but the code for handling the tree data still in `BBjGridExWidget::performGridDataUpdate`. any reason for not removing the code?

**Comment by StephanWald** [comment]
@hyyan correct me if I'm wrong, but I seem to remember you wanted to clean out the code from any remaining tree code?

**Comment by hyyan** [comment]
@StephanWald WIP
