### ISSUE TITLE
Implement Advanced  Selections Features 

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#8]

**Comment by hyyan** [comment]
@StephanWald  

Two new methods have been added to select one or more rows on the grid 

```java 
setSelectedRow(BBjNumber x!)
setSelectedRows(BBjVector x!)
```
Obveiously  `setSelectedRows` needs `GRID_SELECT_ROW` mode in order to work, otherwise only the last index in the array (vector) will be selected (no errors or warnings will be thrown )

**Example**

```java
grid! = new BBjGridExWidget(wnd!,100,0,35,900,563)
grid!.setSelectionMode(grid!.GRID_SELECT_ROW())
grid!.setMultipleSelection(1)

/** selects row 5**/
grid!.setSelectedRow(5)


/** selectes multi rows [2,4,5] */
 v! = new BBjVector()
 v!.addItem(2)
 v!.addItem(4)
 v!.addItem(6)   
 grid!.setSelectedRows(v!)
```

**Comment by hyyan** [comment]
@StephanWald  Added  two new methods to improve selection:

## Methods 
**setGroupSelectsChildren** 

When true, selecting a group will have the impact of selecting all its children
When false, then the group is selectable independently of the child nodes

**seShowSelectionCheckbox**

When true, selection box will be shown in the first column
When false, no checkbox will be displayed.

## Example

```java
grid! = new BBjGridExWidget(wnd!,100,0,35,900,563)

grid!.setEnableFilter(1)
grid!.setMultipleSelection(1)
grid!.setSelectionMode(grid!.GRID_SELECT_ROW())
grid!.setGroupSelectsChildren(1)
grid!.seShowSelectionCheckbox(1)
```

![1](https://user-images.githubusercontent.com/4313420/35042226-0d9bf4a4-fb88-11e7-9300-1f0893c9fdaa.PNG)

![2](https://user-images.githubusercontent.com/4313420/35042230-14bcb82c-fb88-11e7-8ae9-2373de92d9c0.PNG)

**Comment by hyyan** [comment]
@StephanWald 
Added the ability to select/deselect data 

##Methods 

**selectAll** 
Will select all data, if the `filtered` param is passed then only filtered data will be selected

**deselectAll** 
Will deselect all data, if the `filtered` param is passed then only filtered data will be deselected


## Example

```java 
grid! = new BBjGridExWidget(wnd!,100,0,35,900,563)
grid!.selectAll()
/** do some filtering from the grid  */
grid!.deselectAll(1)
```

**Comment by hyyan** [comment]
@StephanWald 

Added the ability to collapse and expand groups 

## Methods 
1. **collapseAll**
2. **expandAll**

## Example 

```java
grid! = new BBjGridExWidget(wnd!,100,0,35,900,563)
grid!.exapndAll()
grid!.collapseAll()
```

**Comment by hyyan** [comment]
@StephanWald 

Added two new method to set visible row/column 

## Methods 
1. **setVisibleRow(BBjNumber index! , BBjString position!)**
Ensures the row index is visible by vertically scrolling the grid. The valid values for positions are {'top', 'middle', 'bottom', undefined/null}. If top, middle or bottom, the grid will scroll the row to place the row at top, middle or bottom.

2. **setVisibleColumn(BBjString columnId!)**
Ensures the column is visible, scrolling the table if needed.

## Example 

```java
grid! = new BBjGridExWidget(wnd!,100,0,35,900,563)
grid!.setVisibleColumn("CUSTOMERID")
grid!.setVisibleRow(50 , grid!.GRID_ROWPOS_MIDDLE())
```

**Comment by StephanWald** [comment]
closing this very broad one; everything that is still missing should become a separate issue then.
