### ISSUE TITLE
improve default sidebar behavior

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#86]
improve the sidebar behavior
- it should start closed but visible already on the JS side (currently opened but visible - the bbj class closes it which makes it flicker and briefly display on slow machines)
- any subsequent setData should retain its status (leave it open or closed after a new setData for fresh data)

**Comment by hyyan** [comment]
@StephanWald 

1. BBj can control which tool panel in the sidebar should be opened, the default sidebar opens the columns tool panel by default, now this is changed in 024b7ebf404e69ccc0e887ebf753ee513484ce8c
**Ex : controll default opened toolpanel :**
`grid!.getSidebar().setDefaulToolpanel(BBjGridExWidgetColumnsToolpanel.getId())`

2. Do not use `setData` for data refresh , this method will cause a full re-render in the client , the state in this case can not be preserved. use `setRowsData` instead , this method will refresh the data in the grid and preserve soring/order & filters.
@see `DataUpdateDemo.bbj`
