### ISSUE TITLE
BUI: ON_GRID_SELECT_ROW event attached to the wrong grid instance if there is more than one grid on the window

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#90]
Run the TwoGridsDemo in BUI. Select a record in the upper grid, then select one in the lower grid. It will fail with an error when selecting the record in the lower grid. Even if you comment out line 39 that registers an extra event on the lower grid you will see this event fired which indicates that it's attached to the wrong grid instance (respectively fired regardless of the grid being selected).

**Comment by hyyan** [comment]
@StephanWald  
BBj was unable to associate the JavaScript event with the corresponding BBj session.
According to the [docs](https://documentation.basis.com/BASISHelp/WebHelp/bbjevents/bbjnativejavascriptevent.htm) `basisDispatchCustomEvent` accepsts a DOM Element and arbitrary JavaScript object unlike the `basisDispatchNativeEvent`  which accepts a JavaScript DOM Event
