### ISSUE TITLE
grid option enableSorting is removed

### ISSUE THREAD

**Issue by hyyan** [BBj-Plugins/BBjGridExWidget#96]
> ag-Grid: since v20, grid options enableSorting and enableServerSideSorting are gone. Instead set sortable=true on the column definition for the columns sorting are allowed on. To migrate from gridOption.enableSorting=true, set gridOptions.defaultColDef.sortable=true

**Comment by harilal** [comment]
How to implement enableServerSideSorting  in the new version?

**Comment by hyyan** [comment]
@harilal All columns are sortable by default if you want to enable/disable sorting for columns using the API method `setSortable`
```java
 grid!.getColumn("CDNUMBER").setSortable(0)
```
